image: node:8.11.3-alpine

pages:
  cache:
    paths:
      - node_modules
    
  script:
    - yarn install --pure-lockfile
    - yarn build
    - rm -rf public && mv build public

  artifacts:
    paths:
      - public

  only:
    - master
