name: Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Install system dependencies
      run: sudo apt-get install build-essential
    - uses: actions/checkout@v1
    - name: Setup environment
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install --pure-lockfile
    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: ./public/
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
